[bell]
animation = "EaseOut"
color = "#c5c0b9"
duration = 200

[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xcb2431"
index = 17

[colors.bright]
black = "0x959da5"
blue = "0x005cc5"
cyan = "0x3192aa"
green = "0x22863a"
magenta = "0x5a32a3"
red = "0xcb2431"
white = "0xd1d5da"
yellow = "0xb08800"

[colors.normal]
black = "0x24292e"
blue = "0x0366d6"
cyan = "0x0598bc"
green = "0x28a745"
magenta = "0x5a32a3"
red = "0xd73a49"
white = "0x6a737d"
yellow = "0xdbab09"

[colors.primary]
background = "0xeeeeee"
foreground = "0x24292f"

[font]
size = 11

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "google-chrome"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control"

[window]
decorations = "full"
opacity = 1.0

[window.dimensions]
columns = 100
lines = 35

[window.padding]
x = 8
y = 8

[window.position]
x = 48
y = 48
