import = ["~/.config/alacritty/alacritty.local.toml"]

[bell]
animation = "EaseOut"
color = "#c5c0b9"
duration = 200

[font.bold]
family = "Cascadia Code NF"
style = "Bold"

[font.normal]
family = "Cascadia Code NF"
style = "Regular"

[font.italic]
family = "Cascadia Code NF"
style = "Italic"

[font.bold_italic]
family = "Cascadia Code NF"
style = "Bold Italic"

[font.offset]
x = 0
y = 2

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"
mods = "Command"

[window]
decorations = "full"
opacity = 1.0

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 16
y = 16

[window.position]
x = 512
y = 512

