import = ["~/.config/alacritty/alacritty.local.toml"]

[bell]
animation = "EaseOut"
color = "#c5c0b9"
duration = 200

[font.bold]
family = "Cascadia Code NF"
style = "Bold"

[font.normal]
family = "Cascadia Code NF"
style = "Regular"

[font.offset]
x = 0
y = 2

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "google-chrome"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[window]
decorations = "full"
opacity = 1.0

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 16
y = 16

[window.position]
x = 256
y = 256

